[server]
port = 8888
[theme]
base = "light"
primaryColor ="#F39C12"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[theme.customCSS]
main = "css/custom_theme.css"
